[project]
name = 'Fitness-Motivation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fitness-goals_]
path = 'contracts/fitness-goals_.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
